/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppEngagementsIdRouteImport } from './routes/app.engagements.$id'
import { Route as ApiPublicRunnerReportRouteImport } from './routes/api/public/runner/report'
import { Route as ApiPublicRunnerRegisterRouteImport } from './routes/api/public/runner/register'
import { Route as ApiPublicRunnerHeartbeatRouteImport } from './routes/api/public/runner/heartbeat'
import { Route as ApiPublicRunnerClaimRouteImport } from './routes/api/public/runner/claim'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEngagementsIdRoute = AppEngagementsIdRouteImport.update({
  id: '/engagements/$id',
  path: '/engagements/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRunnerReportRoute = ApiPublicRunnerReportRouteImport.update({
  id: '/api/public/runner/report',
  path: '/api/public/runner/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerRegisterRoute = ApiPublicRunnerRegisterRouteImport.update({
  id: '/api/public/runner/register',
  path: '/api/public/runner/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunnerHeartbeatRoute =
  ApiPublicRunnerHeartbeatRouteImport.update({
    id: '/api/public/runner/heartbeat',
    path: '/api/public/runner/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRunnerClaimRoute = ApiPublicRunnerClaimRouteImport.update({
  id: '/api/public/runner/claim',
  path: '/api/public/runner/claim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/api/public/runner/claim': typeof ApiPublicRunnerClaimRoute
  '/api/public/runner/heartbeat': typeof ApiPublicRunnerHeartbeatRoute
  '/api/public/runner/register': typeof ApiPublicRunnerRegisterRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/api/public/runner/claim': typeof ApiPublicRunnerClaimRoute
  '/api/public/runner/heartbeat': typeof ApiPublicRunnerHeartbeatRoute
  '/api/public/runner/register': typeof ApiPublicRunnerRegisterRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/api/public/runner/claim': typeof ApiPublicRunnerClaimRoute
  '/api/public/runner/heartbeat': typeof ApiPublicRunnerHeartbeatRoute
  '/api/public/runner/register': typeof ApiPublicRunnerRegisterRoute
  '/api/public/runner/report': typeof ApiPublicRunnerReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/engagements/$id'
    | '/api/public/runner/claim'
    | '/api/public/runner/heartbeat'
    | '/api/public/runner/register'
    | '/api/public/runner/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/engagements/$id'
    | '/api/public/runner/claim'
    | '/api/public/runner/heartbeat'
    | '/api/public/runner/register'
    | '/api/public/runner/report'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/engagements/$id'
    | '/api/public/runner/claim'
    | '/api/public/runner/heartbeat'
    | '/api/public/runner/register'
    | '/api/public/runner/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRunnerClaimRoute: typeof ApiPublicRunnerClaimRoute
  ApiPublicRunnerHeartbeatRoute: typeof ApiPublicRunnerHeartbeatRoute
  ApiPublicRunnerRegisterRoute: typeof ApiPublicRunnerRegisterRoute
  ApiPublicRunnerReportRoute: typeof ApiPublicRunnerReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/engagements/$id': {
      id: '/app/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/app/engagements/$id'
      preLoaderRoute: typeof AppEngagementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/runner/report': {
      id: '/api/public/runner/report'
      path: '/api/public/runner/report'
      fullPath: '/api/public/runner/report'
      preLoaderRoute: typeof ApiPublicRunnerReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/register': {
      id: '/api/public/runner/register'
      path: '/api/public/runner/register'
      fullPath: '/api/public/runner/register'
      preLoaderRoute: typeof ApiPublicRunnerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/heartbeat': {
      id: '/api/public/runner/heartbeat'
      path: '/api/public/runner/heartbeat'
      fullPath: '/api/public/runner/heartbeat'
      preLoaderRoute: typeof ApiPublicRunnerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runner/claim': {
      id: '/api/public/runner/claim'
      path: '/api/public/runner/claim'
      fullPath: '/api/public/runner/claim'
      preLoaderRoute: typeof ApiPublicRunnerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppEngagementsIdRoute: typeof AppEngagementsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEngagementsIdRoute: AppEngagementsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRunnerClaimRoute: ApiPublicRunnerClaimRoute,
  ApiPublicRunnerHeartbeatRoute: ApiPublicRunnerHeartbeatRoute,
  ApiPublicRunnerRegisterRoute: ApiPublicRunnerRegisterRoute,
  ApiPublicRunnerReportRoute: ApiPublicRunnerReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
